### ISSUE TITLE
Bump shapeless version to 2.3.0

### ISSUE THREAD

**Issue by mgttlinger** [netvl/picopickle#14]
I was trying to include picopickle in the benchmark of https://github.com/travisbrown/circe but due to the binary incompatibility between shapeless 2.2.3 and 2.3.0 I was unable to do that.
As the two versions are source compatible this should be as simple as changing the version in the build.

**Comment by netvl** [comment]
Okay, makes sense. I'll try to do it today.

**Comment by mgttlinger** [comment]
Cool, thanks

**Comment by netvl** [comment]
Hmm, it appears it is not that simple. After shapeless switched to macro-compat, my approach for extending its macro bundles in Scala 2.10 had broken. I'll see if I could fix this by switching to macro-compat too.

**Comment by netvl** [comment]
I've just released version 0.2.1 with the updated shapeless dependency.It should be available in maven central soon. Could you please check whether it works now?

**Comment by mgttlinger** [comment]
Tested it, works. Thanks for the quick fix.

**Comment by mgttlinger** [comment]
FYI: Now Picopickle is in the [benchmark on the circe repo](https://github.com/travisbrown/circe#performance)

**Comment by netvl** [comment]
Thanks!
