### ISSUE TITLE
discriminator key configuration broken when using collections backend

### ISSUE THREAD

**Issue by mberndt123** [netvl/picopickle#20]
Hi,

I get the following error message when trying a roundtrip (pickling/unpickling) of a type in my project:
io.github.netvl.picopickle.ExceptionsComponent$ReadException: reading sealed trait hierarchy member, expected object with discriminator key 'something', got Map(something -> A, xs -> Vector(Map(something -> B)))

I managed to reproduce the issue in a tiny example project which I'll attach. The reason I'm using the typelevel scala compiler fork is that it contains a fix for Scala bug SI-7046, which shapeless and thus picopickle is affected by.

[picoPickleTest.tar.gz](https://github.com/netvl/picopickle/files/528349/picoPickleTest.tar.gz)

**Comment by mberndt123** [comment]
I think I found a fix. It turns out that the discriminator is actuall `null` when it reaches `ObjectWithDiscriminatorExtractor.unapply`. Those are typically initialisation order problems, and I was able to make it go away by changing `DefaultSealedTraitDiscriminatorComponent.defaultDiscriminatorKey` from a `val` to a `lazy val`.

**Comment by mberndt123** [comment]
Hey there,

could you give an estimate on when a new release with this fix will be published?

**Comment by netvl** [comment]
I'll try to do it on the weekend.

**Comment by netvl** [comment]
@mberndt123, I've just released 0.3.1 which contains the fix.
