### ISSUE TITLE
Scala 2.12 support?

### ISSUE THREAD

**Issue by rrwright** [netvl/picopickle#22]
I notice that this repo hasn't seen any commits or releases in the last ~year or so. Is this library still maintained and do you plan to support Scala 2.12 and publish a 2.12 build to Maven Central? Thanks!

**Comment by rrwright** [comment]
Something constructive: https://github.com/netvl/picopickle/pull/23

**Comment by netvl** [comment]
Closed by #23

**Comment by rrwright** [comment]
Want to push version 0.3.2 to Maven?
